---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(reticulate)
```

```{python}
from sklearn.metrics import roc_curve, roc_auc_score, auc, classification_report
from sklearn.preprocessing import LabelBinarizer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scikitplot as skplt

```

```{python}
nb_full = pd.read_csv('G:/sta207/project4/Project-4/Naive_Bayes_Full_Result.csv')
nb_opt = pd.read_csv('G:/sta207/project4/Project-4/Naive_Bayes_Optimal_Result.csv')
logit = pd.read_csv('G:/sta207/project4/Project-4/Logistic_Regression_Full_Result.csv')
rdf = pd.read_csv('G:/sta207/project4/Project-4/random_forest.csv')
rdf_r = pd.read_csv('G:/sta207/project4/Project-4/random_forest_r.csv')

nb_full[['y.act', 'y.pred']] = nb_full[['y.act', 'y.pred']].eq('yes').mul(1)
nb_opt[['y.act', 'y.pred']] = nb_opt[['y.act', 'y.pred']].eq('yes').mul(1)
logit[['y.act', 'y.pred']] = logit[['y.act', 'y.pred']].eq('yes').mul(1)
rdf[['y.act', 'y.pred']] = rdf[['y.act', 'y.pred']].eq('yes').mul(1)
rdf_r[['y.act', 'y.pred']] = rdf_r[['y.act', 'y.pred']].eq('yes').mul(1)
```

```{python}
print(classification_report(nb_full['y.act'], nb_full['y.pred']))
```

```{python}
print(classification_report(nb_opt['y.act'], nb_opt['y.pred']))
```

```{python}
print(classification_report(logit['y.act'], logit['y.pred']))
```

```{python}
#print(classification_report(rdf['y.act'], rdf['y.pred']))
```

```{python}
print(classification_report(rdf_r['y.act'], rdf_r['y.pred']))
```

```{r}
nb_full = read.csv('Naive_Bayes_Full_Result.csv')
nb_opt = read.csv('Naive_Bayes_Optimal_Result.csv')
logit = read.csv('Logistic_Regression_Full_Result.csv')
rdf = read.csv('random_forest.csv')
rdf_r = read.csv('random_forest_r.csv')
```

```{r}
library(precrec)
library(ggplot2)

s1 <- nb_full$y.prob.yes
s2 <- nb_opt$y.prob.yes
s3 <- logit$y.prob.yes
s4 <- rdf$yes
s5 <- rdf_r$yes

scores <- join_scores(s1, s2, s3, s5)

l1 <- nb_full$y.act
l2 <- nb_opt$y.act
l3 <- logit$y.act
l4 <- rdf$y.act
l5 <- rdf_r$y.act


labels <- join_labels(l1, l2, l3, l5)

msmdat <- mmdata(scores, labels, modnames = c("Naive Bayes Full", "Naive Bayes Optimal", "Logistic Regression", "Random Forest"))

mscurves <- evalmod(msmdat)

autoplot(mscurves)
```




